apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deploy

spec: 
  replicas: 3
  selector:
    matchLabels:
      env: production
#    matchExpressions:
#      - { key: env, operator: In, values: [ production ] }
  template:
    metadata:
      name: myweb-pod
      labels:
        env: production
    spec:
      containers: 
        - name: myweb-con
          image: srishtigupta20/php-image-from-jenkins:latest 
