apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task4-web-pvc
  labels:
    name: task4webpvc
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
